//location
export const LOCATION_CHANGE = 'LOCATION_CHANGE';
//auth
export const FETCH_TOKEN = 'FETCH_TOKEN';
export const FETCH_TOKEN_FULFILLED = "FETCH_TOKEN_FULFILLED";
export const FETCH_TOKEN_REJECTED = "FETCH_TOKEN_REJECTED";
//homepage
export const FETCH_POSTROLL = 'FETCH_POSTROLL'
export const FETCH_POSTROLL_FULFILLED = 'FETCH_POSTROLL_FULFILLED'
export const FETCH_POSTROLL_REJECTED = 'FETCH_POSTROLL_REJECTED'
//post.fetch
export const FETCH_POST = 'FETCH_POST';
export const FETCH_POST_FULFILLED = "FETCH_POST_FULFILLED";
export const FETCH_POST_REJECTED = "FETCH_POST_REJECTED";
export const FETCH_POST_NOTFOUND = "FETCH_POST_NOTFOUND";
//post.add
export const ADD_POST = 'ADD_POST';
export const ADD_POST_FULFILLED = 'ADD_POST_FULFILLED';
export const ADD_POST_REJECTED = 'ADD_POST_REJECTED';
//post.edit
export const EDIT_POST = 'EDIT_POST';
export const EDIT_POST_FULFILLED = 'EDIT_POST_FULFILLED';
export const EDIT_POST_REJECTED = 'EDIT_POST_REJECTED';
//post.delete
export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_FULFILLED = 'DELETE_POST_FULFILLED';
export const DELETE_POST_REJECTED = 'DELETE_POST_REJECTED';
//commentRoll.fetch
export const FETCH_COMMENTROLL = 'FETCH_COMMENTROLL';
export const FETCH_COMMENTROLL_FULFILLED = 'FETCH_COMMENTROLL_FULFILLED';
export const FETCH_COMMENTROLL_REJECTED = 'FETCH_COMMENTROLL_REJECTED';
//comment.add
export const COMMENT_ADD = 'COMMENT_ADD';
export const COMMENT_ADD_FULFILLED = 'COMMENT_ADD_FULFILLED';
export const COMMENT_ADD_REJECTED = 'COMMENT_ADD_REJECTED';
//comment.edit
export const COMMENT_EDIT = 'COMMENT_EDIT';
export const COMMENT_EDIT_FULFILLED = 'COMMENT_EDIT_FULFILLED';
export const COMMENT_EDIT_REJECTED = 'COMMENT_EDIT_REJECTED';
//comment.delete
export const COMMENT_DELETE = 'COMMENT_DELETE';
export const COMMENT_DELETE_FULFILLED = 'COMMENT_DELETE_FULFILLED';
export const COMMENT_DELETE_REJECTED = 'COMMENT_DELETE_REJECTED';
//profile.fetch
export const FETCH_PROFILE = 'FETCH_PROFILE_REJECTED';
export const FETCH_PROFILE_FULFILLED = 'FETCH_PROFILE_REJECTED';
export const FETCH_PROFILE_REJECTED = 'FETCH_PROFILE_REJECTED'; 
//profile.edit
export const PROFILE_EDIT = 'PROFILE_EDIT';
export const PROFILE_EDIT_FULFILLED = 'PROFILE_EDIT_FULFILLED';
export const PROFILE_EDIT_REJECTED = 'PROFILE_EDIT_REJECTED';
//track
export const PLAY_TRACK = 'PLAY_TRACK';
export const PAUSE_TRACK = 'PAUSE_TRACK';
export const SEEK_TRACK = 'SEEK_TRACK';
//IP
export const FETCH_IP = 'FETCH_IP';
export const FETCH_IP_FULFILLED = 'FETCH_IP_FULFILLED';
export const FETCH_IP_REJECTED = 'FETCH_IP_REJECTED';
//me
export const FETCH_ME = 'FETCH_ME';
export const FETCH_ME_FULFILLED = 'FETCH_ME_FULFILLED';
export const FETCH_ME_REJECTED = 'FETCH_ME_REJECTED';