//location
export const LOCATION_CHANGE = 'LOCATION_CHANGE';
//auth
export const FETCH_TOKEN = 'FETCH_TOKEN';
export const FETCH_TOKEN_FULFILLED = "FETCH_TOKEN_FULFILLED";
export const FETCH_TOKEN_REJECTED = "FETCH_TOKEN_REJECTED";

//homepage
export const FETCH_POSTROLL = 'FETCH_POSTROLL'
export const FETCH_POSTROLL_FULFILLED = 'FETCH_POSTROLL_FULFILLED'
export const FETCH_POSTROLL_REJECTED = 'FETCH_POSTROLL_REJECTED'
//post
export const FETCH_POST = 'FETCH_POST';
export const FETCH_POST_FULFILLED = "FETCH_POST_FULFILLED";
export const FETCH_POST_REJECTED = "FETCH_POST_REJECTED";
export const FETCH_POST_NOTFOUND = "FETCH_POST_NOTFOUND";